# Generated by Django 3.2.16 on 2022-11-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewarder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rewarder.signup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_tasks',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='rewarder.task'),
        ),
    ]
