# Generated by Django 4.0.5 on 2022-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewarder', '0003_auto_20221105_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfacing',
            name='category',
            field=models.CharField(choices=[('E', 'ENTERTAINMENT'), ('N', 'NEWS'), ('S', 'SPORTS')], default='E', max_length=3),
        ),
        migrations.AddField(
            model_name='adminfacing',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='adminfacing',
            name='sub_category',
            field=models.CharField(choices=[('SOC', 'SOCIAL MEDIA'), ('KNO', 'KNOWLEDGE'), ('FAN', 'FAN APP')], default='SOC', max_length=3),
        ),
    ]
