# Generated by Django 4.0.5 on 2022-11-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewarder', '0004_adminfacing_category_adminfacing_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_details',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_tasks',
        ),
    ]
